### ISSUE TITLE
Unable to write GDAL data with no points for output

### ISSUE THREAD

**Issue by Platipipus645** [williamlidberg/Cultural-remains#2]
![1](https://user-images.githubusercontent.com/76967479/177780932-417a1a85-7d01-4cd6-9fe2-e2d6e31ea6b6.png)
I want to load .las files into QGis, and since i couldn't just do that even with LAStools, i tried to install pdal on Miniconda3 and it worked and I made a pipeline. Everything works up until this part where when I say pdal pipeline "C:/Users/PC/Desktop/L/pipeline.json" it just returns as pdal unable to write gdal data with no points for output. 
I'm not sure what to do. 
And in advance, thanks!

**Comment by williamlidberg** [comment]
Hello,

Gdal can be a bit of a hassle to get right. I suggest that you build a docker container with this dockerfile. https://github.com/williamlidberg/Cultural-remains/blob/main/semantic_segmentation/Dockerfile it will install both gdal and Whitebox tools which could be useful for handling las and laz data.

**Comment by Platipipus645** [comment]
Thank you very much!!!
